[onboard]
title = "ニコニコ ボイロ車載動画 年次統計"
keywords = "VOICEPEAK車載 OR VOICEROID車載 OR CeVIO車載 OR ソフトウェアトーク車載 OR A.I.VOICE車載 OR VOICEVOX車載 OR ガイノイドTalk車載 OR Coefont車載"
dist_ylim = [0, 5000]

[travel]
title = "ニコニコ ボイロ旅行動画 年次統計"
keywords = "VOICEROID旅行 OR ソフトウェアトーク旅行"
dist_ylim = [0, 5000]

[fishing]
title = "ニコニコ ボイロフィッシング動画 年次統計"
keywords = "VOICEROIDフィッシング OR ボイスロイド釣り実況 OR ソフトウェアトークフィッシング"
dist_ylim = [0, 20000]

[biim]
title = "ニコニコ biim兄貴リスペクト動画 年次統計"
keywords = "biim兄貴リスペクト OR biim兄貴"
dist_ylim = [0, 40000]

[kitchen]
title = "ニコニコ ボイロキッチン動画 年次統計"
keywords = "VOICEROIDキッチン OR ソフトウェアトークキッチン"
dist_ylim = [0, 20000]

[theater]
title = "ニコニコ ボイロ劇場 年次統計"
keywords = "VOICEROID劇場 OR ソフトウェアトーク劇場"
dist_ylim = [0, 20000]
